version: "3"
services:
  hariadiagnostic:
    image: kelvysb/hariadiagnostic:latest
    hostname: HARIA_Diagnostic
    container_name: HARIA_Diagnostic
    restart: always
    expose:
      - "${DIAGNOSTIC_PORT:-7010}"
    ports:
      - "${DIAGNOSTIC_PORT:-7010}:${DIAGNOSTIC_PORT:-7010}"
    networks:
      - local
    environment:
      - DIAGNOSTIC_PORT=${DIAGNOSTIC_PORT:-7010}
      - MQTT_SERVER=${MQTT_SERVER:?env var MQTT_SERVER not found}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USER=${MQTT_USER:?env var MQTT_USER not found}
      - MQTT_PASSWORD=${MQTT_PASSWORD:?env var MQTT_PASSWORD not found}
      - MQTT_TOPICS_PATTERN=${MQTT_TOPICS_PATTERN:-devices/+/+}
      - MQTT_DEVICE_ID=${MQTT_DEVICE_ID:-Diagnostic}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING:?env var MONGODB_CONNECTION_STRING not found}
      - MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME:-HARIA}
      - AUTH_ISSUER=${AUTH_ISSUER:-www.haria.com}
      - AUTH_SECRET=${AUTH_SECRET:?env var AUTH_SECRET not found}
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_DEFAULT_PASSWORD:-admin}
  hariastatekeeper:
    image: kelvysb/hariastatekeeper:latest
    hostname: HARIA_StateKeeper
    container_name: HARIA_StateKeeper
    restart: always
    expose:
      - "${STATE_KEEPER_PORT:-7020}"
    ports:
      - "${STATE_KEEPER:-7020}:${STATE_KEEPER:-7020}"
    networks:
      - local
    environment:
      - DIAGNOSTIC_PORT=${DIAGNOSTIC_PORT:-7010}
      - MQTT_SERVER=${MQTT_SERVER:?env var MQTT_SERVER not found}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USER=${MQTT_USER:?env var MQTT_USER not found}
      - MQTT_PASSWORD=${MQTT_PASSWORD:?env var MQTT_PASSWORD not found}
      - MQTT_TOPICS_PATTERN=${MQTT_TOPICS_PATTERN:-devices/+/+}
      - MQTT_DEVICE_ID=${MQTT_DEVICE_ID:-Diagnostic}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING:?env var MONGODB_CONNECTION_STRING not found}
      - MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME:-HARIA}
      - ELASTIC_URL=${ELASTIC_URL}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

  hariaintegration:
    image: kelvysb/hariaintegration:latest
    hostname: HARIA_Integration
    container_name: HARIA_Integration
    restart: always
    expose:
      - "${INTEGRATION_PORT:-7030}"
    ports:
      - "${INTEGRATION_PORT:-7030}:${INTEGRATION_PORT:-7030}"
    networks:
      - local
    environment:
      - INTEGRATION_API_KEY=${INTEGRATION_API_KEY:?env var INTEGRATION_API_KEY not found}
      - STATE_KEEPER_PORT=${INTEGRATION_PORT:-7030}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING:?env var MONGODB_CONNECTION_STRING not found}
      - MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME:-HARIA}
      - ELASTIC_URL=${ELASTIC_URL}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

networks:
  local:
    driver: bridge
