// <auto-generated by="the Blazor I18n Text compiler" />
namespace HARIA.Emulator.I18nText
{
    public partial class Text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Add"</summary>
        public string Add;

        /// <summary>"HARIA-DE"</summary>
        public string App_name;

        /// <summary>"HARIA-DE"</summary>
        public string AppName;

        /// <summary>"Configurations"</summary>
        public string Configurations;

        /// <summary>"Dashboard"</summary>
        public string Dashboard;

        /// <summary>"Devices"</summary>
        public string Devices;

        /// <summary>"Off"</summary>
        public string Off;

        /// <summary>"On"</summary>
        public string On;

        /// <summary>"Remove"</summary>
        public string Remove;

        /// <summary>"State"</summary>
        public string State;

        /// <summary>"Toggle"</summary>
        public string Toggle;
    }
}
