// <auto-generated by="the Blazor I18n Text compiler" />
namespace HARIA.Emulator.I18nText
{
    public partial class Text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Actuator"</summary>
        public string Actuator;

        /// <summary>"Add"</summary>
        public string Add;

        /// <summary>"Add default test data"</summary>
        public string AddTestData;

        /// <summary>"Administrator privileges user"</summary>
        public string AdminOnly;

        /// <summary>"HARIA-DE"</summary>
        public string AppName;

        /// <summary>"Configurations"</summary>
        public string Configurations;

        /// <summary>"Dashboard"</summary>
        public string Dashboard;

        /// <summary>"Details"</summary>
        public string Details;

        /// <summary>"Error"</summary>
        public string Error;

        /// <summary>"Wrong user or password"</summary>
        public string LoginFail;

        /// <summary>"No test data"</summary>
        public string NoData;

        /// <summary>"Nodes"</summary>
        public string Nodes;

        /// <summary>"Off"</summary>
        public string Off;

        /// <summary>"On"</summary>
        public string On;

        /// <summary>"Password"</summary>
        public string Password;

        /// <summary>"Remove"</summary>
        public string Remove;

        /// <summary>"See logs for more information about this error"</summary>
        public string SeeLogs;

        /// <summary>"Sensor"</summary>
        public string Sensor;

        /// <summary>"Sign in"</summary>
        public string SignIn;

        /// <summary>"Sign out"</summary>
        public string SignOut;

        /// <summary>"Something went wrong"</summary>
        public string SomethingWrong;

        /// <summary>"State"</summary>
        public string State;

        /// <summary>"Toggle"</summary>
        public string Toggle;

        /// <summary>"User"</summary>
        public string User;
    }
}
