// <auto-generated by="the Blazor I18n Text compiler" />
namespace HARIA.Emulator.I18nText
{
    public partial class DefaultData : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Action"</summary>
        public string Action;

        /// <summary>"Actuator"</summary>
        public string Actuator;

        /// <summary>"Bedroom"</summary>
        public string BedRoom;

        /// <summary>"Kitchen"</summary>
        public string Kitchen;

        /// <summary>"Living Room"</summary>
        public string LivingRoom;

        /// <summary>"Node"</summary>
        public string Node;

        /// <summary>"Sensor"</summary>
        public string Sensor;

        /// <summary>"Cen�rio de teste"</summary>
        public string TestScenario;
    }
}
